services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      CATALOG_BASE_URL: "https://evengo.space"
    # или подтянуть из .env файла рядом с compose:
    # env_file:
    #   - ./.env
